name: Push Workflow
on: push

jobs:
    code-quality:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        - uses: actions/setup-node@v2
          with:
            registry-url: 'https://npm.pkg.github.com'
            node-version: 14.15.3
        - name: Install
          run: yarn install
          env:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
        - name: Lint
          run: yarn lint
        - name: Format
          run: yarn format:check
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}              
        - uses: actions/setup-node@v2
          with:
            registry-url: 'https://npm.pkg.github.com'
            node-version: 14.15.3

        - name: Install
          run: yarn install
          env:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
        - name: Unit Tests
          run: yarn test:unit

            
  
